### ISSUE TITLE
Get-PowerBIReport -Scope Organization and deleted reports

### ISSUE THREAD

**Issue by asocorro** [microsoft/powerbi-powershell#105]
When I run Get-PowerBIReport -Scope Organization I get deleted reports but there is no way to filter them out (even afterwards, as there is no "active" property present).  On the other hand, if the scope is Individual, only active reports are returned.  Is there a way to exclude deleted reports when the scope is Organization?

**Comment by demetrioi** [comment]
This is a must have filter.

**Comment by CattieCat** [comment]
Thank you for the feedback. We are planning change for PowerShell to include all API abilities, and this will be included.
Currently you can use https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.profile/invoke-powerbirestmethod?view=powerbi-ps to call https://docs.microsoft.com/en-us/rest/api/power-bi/admin/reports_getreportsasadmin with desired filter.
