### ISSUE TITLE
Power BI - Moving Average per Monthly Visualization

### ISSUE THREAD

**Issue by UtkuU** [microsoft/powerbi-powershell#134]
I have a dataset which has all data history of personel skill levels. I want to get for each person/each skill latest date skill levels for each month and show the moving average of all peoples monthly bases on bar chart.

I've also another date table (DateTbl) which has year, month & lastday of month columns(DDate)

main database is something like;

DataLog:

  ItemNo  | UserID | Skill_Id | Date    | Skill_lvl 
_____________________________________________________
    1     |  1     |   1   | 08.03.2019 |    1  
    2     |  1     |   1   | 08.04.2019 |    1  
    3     |  1     |   1   | 08.05.2019 |    1  
    4     |  1     |   2   | 08.03.2019 |    1  
    5     |  1     |   2   | 08.04.2019 |    1  
    6     |  2     |   1   | 08.04.2019 |    1  
    7     |  2     |   1   | 08.05.2019 |    1  
    8     |  2     |   2   | 08.04.2019 |    1  
    9     |  2     |   2   | 08.05.2019 |    1  
I want to get monthly moving average skill lvl graph; For instance:

for 3th month calculation needs to be done with itemNo: 1-4
for 4th month calculation needs to be done with itemNo: 2-5-6-8
for 5th month calcualtion needs to be done with itemNo: 3-5-7-9
I have create a measure as;

``
Moving_Average = 
AVERAGEX(
     SUMMARIZE(
        DataLog;
        DataLog[UserID];
        DataLog[Skill_Id];
        "Moving_Average2";
        CALCULATE(
            SUM(DataLog[Skill_lvl]);
            FILTER(
                DataLog;
                DataLog[Date]<=MAX(DateTbl[DDate])
             )
         )
    );
    [Moving_Average2]
)
``

But this is not working very well during visualization and giving each month similar value on average and also graph is showing at the end of year as date table goes on.

How should I configure the model for this kind of issue?

**Comment by nandemoii** [comment]
@UtkuU I think you'll be able to find better help by asking this question on the [Power BI Community forums](https://community.powerbi.com/).
