### ISSUE TITLE
Add-PowerBIWorkspaceUser doesn't accept 'Viewer' for -AccessRight

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/powerbi-powershell#177]
When trying to add a user to a Workspace with the Add-PowerBIWorkspaceUser cmdlet, you are unable to assign the 'Viewer' role via the -AccessRight parameter.

```powershell
Add-PowerBIWorkspaceUser -Workspace (Get-PowerBIWorkspace -Name SomeWorkspace) -UserPrincipalName 'some.user@contoso.com' -AccessRight Viewer
```
Instead of this working, the following error is returned:
```powershell
Add-PowerBIWorkspaceUser : Cannot bind parameter 'AccessRight'. Cannot convert value "Viewer" to type "Microsoft.PowerBI.Common.Api.Workspaces.WorkspaceUserAccessRight". 
Error: "Unable to match the identifier name Viewer to a valid enumerator name. Specify one of the following enumerator names and try again:
Member, Admin, Contributor"
At line:1 char:146
```

**Comment by asyncoder** [comment]
I do confirm, I'm getting the same error! Seems the value"Viewer" is not listed at the AccessRight enumertor.

**Comment by q0-0n** [comment]
It should be added to src/Common/Common.Api/Workspaces/WorkspaceUserAccessRight.cs I assume.

**Comment by 681113366** [comment]
Unfortunately, this is still not supported in the PowerBI powershell cmdlets nor in the REST Api.

**Comment by DaveRuijter** [comment]
Would be great if this can be added soon :)

**Comment by nrablin** [comment]
This is an important fix for any DevOps CICD process

**Comment by Embedded82** [comment]
Any timeline for this?

**Comment by DNOW-BrentPearce** [comment]
This seems like such a simple issue to fix. Any update?

**Comment by alexmahrou** [comment]
I concur!!! I had to go in and click 300 times today when sharing a report to "depermission" folks 😜

`Invoke-PowerBIRestMethod -Url 'groups/some-long-hash/users' -Method POST -Body (@{identifier='someEmail@whatever.com'; groupUserAccessRight='Viewer'; principalType='User'} | ConvertTo-Json -Depth 2 -Compress) ` <-- No dice

**Comment by mrvdsah** [comment]
It's one year later but still no support. This seems to be an easy fix.

**Comment by Embedded82** [comment]
Is this now supported? It would be nice to get this done!

**Comment by Embedded82** [comment]
@inthemedium @kenakamu @CodeCyclone @CattieCat can you please give us a feedback?
It is almost 2 years now!
Where is the roadblock here?

**Comment by CattieCat** [comment]
Change already made in https://github.com/microsoft/powerbi-powershell/commit/036b3561d3b37b45934d092b817ecc0745cbbae9#diff-900436a0aad5c72640ff60fcc243fed6af7eac2ae0ecafc9ba1e07141b0c616a
