### ISSUE TITLE
Get-PowerBIActivityEvents doesn't return activities when activities exist

### ISSUE THREAD

**Issue by DAZCUK46** [microsoft/powerbi-powershell#191]
Get-PowerBIActivityEvents doesn't return data when activity data exists in the audit log.

Exported Power BI activity log data for past 90 days within the Security & Compliance Center to compare results from PS 
When using Get-PowerBIActivityEvents it doesn't return data for any date in past 90 days other than 26th September when activity exists on other days

Example: 

Doesn't return data but exists in the export from Security & Compliance Cener:  Get-PowerBIActivityEvents -StartDateTime 2019-08-13T00:00:01 -EndDateTime 2019-08-13T23:59:01  -ResultType JsonString

Returns data and exists in the export from Security & Compliance Cener:  Get-PowerBIActivityEvents -StartDateTime 2019-09-26T00:00:01 -EndDateTime 2019-09-26T23:59:01  -ResultType JsonString

![PBIActivityEvents from PS (20190926)](https://user-images.githubusercontent.com/29930723/66195678-062f8480-e68f-11e9-895e-cd09437e74a8.JPG)
![PBIActivityEvents from PS (20190813)](https://user-images.githubusercontent.com/29930723/66195681-06c81b00-e68f-11e9-9b8e-e9b8c4d3841b.JPG)
![PBIActivityEvents from Security   Compliance Center (20190813)](https://user-images.githubusercontent.com/29930723/66195683-06c81b00-e68f-11e9-8887-e9d71a569c66.JPG)

**Comment by Guavaq** [comment]
I took am not getting and results when I run the PowerShell command.

I am the Tenant Admin and all that i get back is []

**Comment by krishb1** [comment]
I have tested this API and I see quite bit of audit events missing.

I don’t see any activity for the entire month of Oct and most part of Sep. Has any one tested to see if they see all 3 months of activities?
This message has been marked as Medtronic Controlled

**Comment by CodeCyclone** [comment]
After releasing the cmdlet the service ran into an issue on an external component that has caused the API to return incorrect data. We are disabling the API waiting for a fix so the cmdlet will receive a friendly error message till the fix is rolled out. ETA for the fix in the API is early December.

**Comment by beckerben** [comment]
Assume the error while it is disabled looks something like this?

```
CategoryInfo          : NotEnabled: (Microsoft.Power...BIActivityEvent:GetPowerBIActivityEvent) [Get-PowerBIActivityEvent],  
   Exception
+ FullyQualifiedErrorId : Microsoft.PowerBI.Commands.Profile.Errors.PowerBIRestExceptionRecord,Microsoft.PowerBI.Commands.Admi 
   n.GetPowerBIActivityEvent
```

**Comment by alisalih1** [comment]
I am getting an error as below. I logged in fine, I am a Global Admin in the tenant. 
![image](https://user-images.githubusercontent.com/21177498/71558503-3e422b80-2a22-11ea-83cf-9b3d6a1c0051.png)

**Comment by CoryAMoore** [comment]
@alisalih1 I believe the date range is limited to a single day currently.  Have you tried pulling only one day already?

**Comment by alisalih1** [comment]
> @alisalih1 I believe the date range is limited to a single day currently. Have you tried pulling only one day already?

@CoryAMoore - Thanks for the input. I wasn't aware of that 1-day, so I just tried it. But it is still a no-go on my end. 

![image](https://user-images.githubusercontent.com/21177498/71581957-e2d17580-2ad5-11ea-84ba-12d58418b873.png)

**Comment by CoryAMoore** [comment]
@alisalih1 Can you try the following and see if this works for you?

$pbiactivities = Get-PowerBIActivityEvent -StartDateTime '2019-12-25T00:00:00.000' -EndDateTime '2019-12-25T11:59:59.999' | ConvertFrom-Json

**Comment by alisalih1** [comment]
> $pbiactivities = Get-PowerBIActivityEvent -StartDateTime '2019-12-25T00:00:00.000' -EndDateTime '2019-12-25T11:59:59.999' | ConvertFrom-Json

@CoryAMoore - wohaa... That certainly worked. I am a bit mind-blown here that 1 ms is the difference.

**Comment by CoryAMoore** [comment]
Glad that worked for you.  It took me several tries to get it working.  And I also found that you can only go back a maximum of 30 days, so for example, if you run it today the furthest day you could pull would be 2019-12-01.  If you pull 2019-11-30 today, you would get no results.  I'm looking forward to it being enhanced to pull more than one day at a time and for a longer range similar to what's available in the O365 Audit Logs.

**Comment by DAZCUK46** [comment]
@CodeCyclone 

Can confirm this issue has been resolved so closing thanks.

I have posted a new issue on Power BI Community Forums relating to the newly released Get Activity Events API as i'm experiencing the same issue as this one see:
[https://community.powerbi.com/t5/Developer/Get-Activity-Events-API-doesn-t-return-activities-when/m-p/900516#M21998](url)
