### ISSUE TITLE
Connect-PowerBIServiceAccount Issue using Azure Runbook

### ISSUE THREAD

**Issue by toku-ecco** [microsoft/powerbi-powershell#206]
Hi!

I am trying to retrieve some information from our corporate Power BI service using Azure Automation Runbook. That simple cmdlet works just fine on my PC but somehow does not in the Runbook. Looks to me that it cant communicate with the Power BI Service. It is running on a different subscription, resource group and location but within the same tenant.

Runbook just gives me this message:
"The runbook job was attempted 3 times, but it failed each time.  Common reasons that runbook jobs fail can be found here:  https://docs.microsoft.com/en-us/azure/automation/automation-troubleshooting-automation-errors "

The code is very simple, tried with two methods of passing credentials. 
```
# $pbipassword = ConvertTo-SecureString '*******'' -AsPlainText -Force
# $powerbicredentials = New-Object System.Management.Automation.PSCredential ('*******', $pbipassword)

$powerbicredentials = Get-AutomationPSCredential -Name "Power BI Service User"

Connect-PowerBIServiceAccount -Credential $powerbicredentials 
```

**Comment by toku-ecco** [comment]
Problem covered already here, no solution yet:
https://github.com/microsoft/powerbi-powershell/issues/190

**Comment by khouloudbelhaj** [comment]
@toku-ecco  : Is there any update on this issue? Have you tried working with service principal and creating a function?
