### ISSUE TITLE
Get-PowerBIWorkspace // UserPrincipalName for the AccessRight available

### ISSUE THREAD

**Issue by AH-MT-MSFT** [microsoft/powerbi-powershell#207]
After opening PowerShell in Admin role and installing the appropriate modules,

Use : Connect-PowerBIServiceAccount to connect to the appropriate account

Use : Get-PowerBIWorkspace -All -Scope Organization | Where {($_.Type -eq "Workspace")} | FL 

To return the  AccessRight  AND UserPrincipalName of workspaces

UserPrincipalName is BLANK

**Comment by AH-MT-MSFT** [comment]
Solution : 

Try to update the cmdlets using the command:

Update-Module MicrosoftPowerBIMgmt

Once that is done, try this command:

$workspace = Get-PowerBIWorkspace -Id "<<WorkspaceId>>" –Scope Organization

$workspace.Users | Select Identifier , AccessRight

Please update the MSFT Documentation accordingly.

**Comment by Sea421** [comment]
Wow thanks!

**Comment by AH-MT-MSFT** [comment]
> Wow thanks!

Welcome, Sea421!

**Comment by CattieCat** [comment]
Issue is addressed and will be available in next release
