### ISSUE TITLE
Get-PowerBIWorkspace returns uncomplete data

### ISSUE THREAD

**Issue by Sea421** [microsoft/powerbi-powershell#212]
Hi team,

Get-PowerBIWorkspace returns uncomplete data.
I have called following scripts

### Code 1
```
$workspaces = Get-PowerBIWorkspace -scope Organization -All
$allworkspaces = @()

foreach($workspace in $workspaces)
    {
        $_workspace = @{}
        $_workspace.WorkSpaceId = $workspace.Id 
        $_workspace.WorkspaceName = $workspace.Name   
        $_workspace.WorkspaceType = $workspace.Type 
        $allworkspaces += New-Object -TypeName psobject -Property $_workspace
    }

```
### Code 2
```
$workspaces = Get-PowerBIWorkspace -scope Organization -Include Reports -All
$allworkspaces = @()

foreach($workspace in $workspaces)
    {
        $_workspace = @{}
        $_workspace.WorkSpaceId = $workspace.Id 
        $_workspace.WorkspaceName = $workspace.Name   
        $_workspace.WorkspaceType = $workspace.Type 
        $allworkspaces += New-Object -TypeName psobject -Property $_workspace
    }
```

The returned workspace data are mismatching.
Code 1: deduplicated workspaces count: 28832
Code 2: deduplicated workspaces count: 35039

If group by WorkspaceType :

Code 1: deduplicated workspaces count: PersonalGroup - **22308**, Group - 6192, Workspace - 332
Code 2: deduplicated workspaces count: PersonalGroup - **28515**, Group - 6192, Workspace - 332

MicrosoftPowerBIMgmt version 1.0.840

Is here someone faced with the same issue? Please help me

**Comment by CattieCat** [comment]
This issue regarding personal group should have been fixed
