### ISSUE TITLE
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array

### ISSUE THREAD

**Issue by rajaprad** [microsoft/powerbi-powershell#226]
Hi,

I am getting the below error when trying to use the command **Get-PowerBIWorkspace**

**Error**: Attempted to access an element as a type incompatible with the array.
**Module Version:** 

Binary     1.0.326    MicrosoftPowerBIMgmt.Profile
Binary     1.0.326    MicrosoftPowerBIMgmt.Workspaces

**Powershell:**

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  752

**Comment by Mwalima** [comment]
same here
 Get-PowerBIWorkspace
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array.
At line:1 char:1
+ Get-PowerBIWorkspace
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspace], ArrayTypeMis 
   matchException
    + FullyQualifiedErrorId : Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.Commands.Workspa 
   ces.GetPowerBIWorkspace



Version    Name                                Repository           Description                                                        
-------    ----                                ----------           -----------                                                        
1.0.867    MicrosoftPowerBIMgmt                PSGallery            Microsoft Power BI PowerShell - All cmdlets for Microsoft Power BI 


Version    Name                                Repository           Description                                                        
-------    ----                                ----------           -----------                                                        
1.0.867    MicrosoftPowerBIMgmt.Workspaces     PSGallery            Microsoft Power BI PowerShell - Workspace cmdlets for Microsoft ...

**Comment by CattieCat** [comment]
Please see https://github.com/microsoft/powerbi-powershell/issues/261
