### ISSUE TITLE
Get-PowerBIWorkspace -Scope Organization -Include All -All is having issues in returning Personal Workspaces

### ISSUE THREAD

**Issue by aexley** [microsoft/powerbi-powershell#235]
When running 

`Get-PowerBIWorkspace -Scope Organization -Include All -All | Export-CSV "$PSScriptRoot\Workspaces.csv" -NoTypeInformation -Append`

against an environment it is returning all non-personal workspaces correctly but is having issues with personal workspaces. I am finding missed and duplicated personal workspaces in the return.

Each run it is a different result in regards the personal workspaces.

**Comment by CattieCat** [comment]
This should have been fixed.
