### ISSUE TITLE
Add debug (verbose) information that the public GetEnvironments doesn't work

### ISSUE THREAD

**Issue by Styxxy** [microsoft/powerbi-powershell#253]
See below the referenced code. If the HTTP call fails, currently the error is swallowed up. However it would be much better to add a DEBUG line so when executing with the -Verbose command, at least we can troubleshoot what is going wrong.

In my case I had to read all code to figure out why the cmdlet was failing on my server (we have quite strict security requirements, and limit very much the outbound traffic from servers to the internet).

Also the comment mentions in the rare case the endpoint is not accessible, we should use a custom discovery endpoint; is this somewhere documented?

https://github.com/microsoft/powerbi-powershell/blob/d5b38fafa17ee576d38071d793b9760ad1fc8498/src/Common/Commands.Common/PowerBISettings.cs#L99-L122

FYI
The root cause of the problem I was facing is the same as issue #248 .
This issue is still valid I think, as it is about adding debug information to the function(s).

**Comment by jayanth2830** [comment]
@Styxxy Thanks for pointing it out, this code was implemented in a bit of hurry to quickly provide support for a custom cloud environment that have their own authentication and API endpoints. We will add debug info for when an exception is thrown. 

CustomEnvironment and DiscoveryUrl parameters are discussed here: https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.profile/Connect-PowerBIServiceAccount?view=powerbi-ps but these should not be applicable to you and in most cases. You would just use Connect-PowerBIServiceAccount without these parameters.
