### ISSUE TITLE
Resolve-PowerBIError Needs the result returned exposed

### ISSUE THREAD

**Issue by awilbourn** [microsoft/powerbi-powershell#254]
Trying to work with devops as CICD has really been frustrating. There are not enough details to any exception thrown, where if you run in powershell locally and use fiddler you can get some sort of hint as to what the issue is. Please expose in the object the returned messages from the API call so it can help know what to focus on. I will open a ticket with support as I have one that makes no sense at all. I can take a stage in my release and copy to have for a QA stage, the slight code changes are just for parameter updates for the environment to adjust the connection strings. In devops it fails only for the one workspace in the release, but if I take the exact code and run it locally in PowerShell it works every time no errors. It would seem like what is being sent is not the right details to have updated, but all you get is System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request). At least locally  you can figure out more details, but as it does not fail locally very frustrating. 

This may be more of a wish list, but to me it does not work as I would expect in development it needs to expose all the context of what it had at the time of exception, so just an HTTP context dump.

**Comment by jayanth2830** [comment]
@awilbourn Thanks for creating this issue. We have a work item on our end to log failures in a more robust way. We will get to it as soon as we have capacity to do so.
