### ISSUE TITLE
"get-PowerBiWorkspace" giving error like 'incompatible with the array'

### ISSUE THREAD

**Issue by abhijit-sarkar-std** [microsoft/powerbi-powershell#296]
Hi,

"Get-PowerBiWorkspace " is giving error like below. I tried to execute in VS-Code, ISE and Powershell -Noprofile, but no luck. Please help me to resolve this. 

![image](https://user-images.githubusercontent.com/74673983/119832867-3559d000-bf1c-11eb-9408-89305acf2384.png)

I am using PowerShell 5.1 . Below is list of modules are present in my machine.

**Newtonsoft module::**

MDStreamVersion : 131072
FullyQualifiedName : C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.2\PreloadAssemblies\Newtonsoft.Json.12.0.3.dll
ModuleVersionId : 2676a2da-6edc-420e-890e-d28aa4572ee5
MetadataToken : 1
ScopeName : Newtonsoft.Json.dll
Name : Newtonsoft.Json.12.0.3.dll
Assembly : Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
CustomAttributes : {}
ModuleHandle : System.ModuleHandle

![image](https://user-images.githubusercontent.com/74673983/119833013-5cb09d00-bf1c-11eb-83a2-20f5bf96a2a7.png)

 
**MicrosoftPowerBIMgmt module::**
![image](https://user-images.githubusercontent.com/74673983/119832695-0c393f80-bf1c-11eb-838d-4ed727b54c6d.png)

I have uninstalled MicrosoftPowerBIMgmt and Newtonsoft and installed both again.

**Comment by CattieCat** [comment]
This looks like a compatible issue with newtonsoft.json which we have not figured out yet. It should work if you switch to PowerShell 7

**Comment by abhijit-sarkar-std** [comment]
Thanks... I have updated to PowerShell.
