### ISSUE TITLE
Add, list and remove users in manage permissions section

### ISSUE THREAD

**Issue by oskaruchanski** [microsoft/powerbi-powershell#298]
With new functionalities of managing users separately in reports and datasets within the workspace currently the only option is to inspect and do changes only via UI/browser. PowerShell cmdlets provide those admin activities only at workspace level and it would be a massive improvement to have same options dedicated to reports and datasets as well.

**Comment by CattieCat** [comment]
Thanks for feedback. We have it in our backlog but no locked ETA yet
