### ISSUE TITLE
Azure Runbook still return error when using Get-PowerBIActivityEvent 

### ISSUE THREAD

**Issue by wikri87** [microsoft/powerbi-powershell#307]
Hi,

I'm struggling to make my **azure account automation runbook** work. 
Logging using `Login-PowerBIServiceAccount` is working correctly, but with these commands, `Get-PowerBIActivityEvent`, `Get-PowerBIWorkspace` I get the error: 
`Attempted to access an element as a type incompatible with the array.`

I can't use PowerShell -NoProfile in a runbook and I can't downgrade `MicrosoftPowerBIMgmt` module. I did not have this issue in a previous version of the module. The actual version is 1.2.0.0.

Can you help me fix this?

Thank you,

WIKRI

**Comment by CattieCat** [comment]
To mitigate your issue, Are you not able to uninstall and reinstall
specific previous version like this?
https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-previous-version

I believe we had a case of user is using other module and a very old
version of Newtonsoft.json is loaded and caused our module not be able to
find the required version of newtonsoft module. So please check that as
well. I'll follow up with the dev who actually deal with this issue next
week.

**Comment by wikri87** [comment]
I have found a way to install previous version of MicrosoftPowerBIMgmt , I tried V1.0.840 without success. I also have Newtonsoft.Json Version=6.0.0.0. If you get the previous version that works please let me know. Thank you!

**Comment by kevarnold972** [comment]
I see this is closed, but I don't see the solution. @wilkri87 tried earlier versions unsuccessfully. I have the same issue with runbooks on different tenants. The latest one I created a new automation account and added the PowerBI modules, but I get the same error. Should I open a different issue or continue with this one?

**Comment by CattieCat** [comment]
Sorry closed without comment by mistake. This issue is due to you have lower version of Newtonsoft.Json than requested. Please reach out to Azure Function / Azure Runbook support for help since you cannot use -NoProfile. Our module cannot be responsible for settings in your PowerShell environment.
