### ISSUE TITLE
Connect-PowerBIServiceAccount doesn't work for MFA-enabled accounts in PowerShell Core

### ISSUE THREAD

**Issue by edfreeman** [microsoft/powerbi-powershell#309]
Testing out the new functionality after reading this blog: [Heads up: breaking change coming to Power BI PowerShell Cmdlets](https://powerbi.microsoft.com/en-us/blog/heads-up-breaking-change-coming-to-power-bi-powershell-cmdlets/)

I'm using PowerShell Core and have an MFA-enabled account. I get the error:

```
Connect-PowerBIServiceAccount: One or more errors occurred. (Error Acquiring Token:
Interactive signin with MSAL is not available in current version with your set up. Please use '-Credential (Get-Credential)' instead.)
```

i.e. I'm hitting the error in the code [here](https://github.com/microsoft/powerbi-powershell/blob/feb13ccf200d5cbf40e11fb38129983acb37af2b/src/Common/Common.Authentication/WindowsAuthenticationFactory.cs#L74).

But I can't use the "username+password" suggestion, because I have MFA enabled on my account. 

The cmdlet works on Windows PowerShell because that supports interactive login, but it seems I have no way of using this cmdlet from PowerShell Core. This seems like a pretty big deal.

MicrosoftPowerBIMgmt version: 1.2.0

PSVersion: 7.1.2
PSEdition: Core
GitCommitId: 7.1.2
OS: Microsoft Windows 10.0.19042
Platform: Win32NT
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0

**Comment by talk2rick** [comment]
Acquiring token interactively works in PS Core (.NET Core). According to this doc [https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively], use `WithParentActivityOrWindow()` to get the prompt to show. You can also test with `WithUseEmbeddedWebView()`. Also reference this PS module [https://github.com/AzureAD/MSAL.PS/blob/master/src/New-MsalClientApplication.ps1] and this [https://github.com/AzureAD/MSAL.PS/blob/master/src/Get-MsalToken.ps1]. Look at `PublicClient-Interactive scope`

**Comment by CattieCat** [comment]
Thank you for the suggestion above. It's related to a security requirement
as MSAL interactive login for PowerShell core requires localhost as
loopback URI. I'm planning to address this in next release shortly.

**Comment by CattieCat** [comment]
New version should resolve your issue https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt/1.2.1026

**Comment by edfreeman** [comment]
Brilliant. Thanks @CattieCat!
