### ISSUE TITLE
Export-PowerBIReport preferClientRouting - 403 Forbidden

### ISSUE THREAD

**Issue by kerski** [microsoft/powerbi-powershell#339]
I was trying to use Export-PowerBIReport or Invoke-PowerBIRestMethod to export a Power BI Report (~25MB in size) and I'm getting a 500 internal server error.  After reviewing the API documentation (https://docs.microsoft.com/en-us/rest/api/power-bi/reports/export-report-in-group) I see this note:

"As a workaround for fixing timeout issues, you can set preferClientRouting to true.
Large files are downloaded to a temporary blob. Their URL is returned in the response and stored in the locally downloaded PBIX file."

When I add that (https://api.powerbi.com/v1.0/myorg/groups/{groupId}/reports/{reportId}/export?preferClientRouting=true) I get a 403 Forbidden.  I'm not sure if there is a header I must pass, but I'm the Power BI admin on the tenant and I'm an admin on the workspace.  The workspace is also not in a large dataset format at the moment.

Is there an example out there for preferClientRouting working?

**Comment by kerski** [comment]
So I've tried this on 3 different tenants, and I am only able to replicate the 403 error on Power BI instances on East 2.  On East 2, the workspace can be Pro, Premium Per User, or Premium and I get the same result (403).

**Comment by JamesDBartlett3** [comment]
@kerski, Have you tried passing the `preferClientRouting` parameter in the body of the request? I just tested this on a 600+MB PBIX file, and it worked like a charm:
```Invoke-RestMethod -Uri "https://api.powerbi.com/v1.0/myorg/groups/$workspaceID/reports/$reportID/Export" -Method GET -Headers $headers -ContentType "application/octet-stream" -Body '{"preferClientRouting":true}' -ErrorAction SilentlyContinue -OutFile $targetFilePath```

**Comment by kerski** [comment]
Looks like is was an East 2 issue for few weeks, but not seeing it anymore.  Thanks!

**Comment by ScubaAlex-WPG** [comment]
I am experiencing something similar. I have tried @JamesDBartlett3 approach, but getting a verb error. **Invoke-RestMethod : Cannot send a content-body with this verb-type.**
@kerski were you able to resolve this?

**Comment by JamesDBartlett3** [comment]
@ScubaAlex-WPG, it looks like this was an intermittent issue per @kerski's earlier comment. 
If you're looking for help with `Invoke-RestMethod` in PowerShell, you should join the PowerShell community on [Slack](https://powershell.slack.com) or [Discord](https://discord.gg/powershell).
