### ISSUE TITLE
Support Get-Credential without requiring a ServicePrincipal

### ISSUE THREAD

**Issue by KayUnkroth** [Microsoft/powerbi-powershell#59]
Connect-AzureAD and Connect-MsolService support the -Credential parameter without any additional ServicePrincipal requirements. Login-PowerBI (Connect-PowerBIServiceAccount) should do the same. 
This should work:
$cred = Get-Credential
Login-PowerBI -Credential $cred

**Comment by fmms** [comment]
Yes I would very much need support for this as well. I have a script that runs perfectly on my local machine asking for the username and password the first time it is executed.
However when running this unattended in VSTS I need support to pass username / password. 

```
# $cred = Get-Credential
# Login-PowerBIServiceAccount -Credential $cred
cmdlet Connect-PowerBIServiceAccount at command pipeline position 1
Supply values for the following parameters:
ServicePrincipal:
```

**Comment by CodeCyclone** [comment]
This will be in the next release later this week.

**Comment by CodeCyclone** [comment]
Released in https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt/1.0.342
