### ISSUE TITLE
Failure trying to import-module

### ISSUE THREAD

**Issue by JosephOBrien1234** [Microsoft/powerbi-powershell#63]
On a windows 10 machine:  

Error:
PS H:\> Import-Module -Name MicrosoftPowerBIMgmt
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.
They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
At line:1 char:1
+ Import-Module -Name MicrosoftPowerBIMgmt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand

$PSVERSIONTABLE

Name                           Value
----                           -----
PSVersion                      5.1.14393.2363
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2363
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by SQLIO** [comment]
Also having the exact same problem; executionpolicy is set to unrestricted. Issue appears to be with the .profile module
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference 
assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
At line:1 char:1
+ Import-Module MicrosoftPowerBIMgmt.profile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by SQLIO** [comment]
stefvsignup solved this for me - install .net framework

**Comment by HeinBehrensRR** [comment]
Getting the same error in Azure automation when trying to install module from the module gallery.

**Comment by CodeCyclone** [comment]
Should be fixed in https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt/1.0.326.
