### ISSUE TITLE
Login to PBI as a different user

### ISSUE THREAD

**Issue by Stefvsignup** [Microsoft/powerbi-powershell#69]
Hi all, I have two Azure accounts, one is my regular account and the other is an admin account. When I try Login-PowerBI a popup appears, I fill in the admin account username and click next, then however I'm getting automatically signed to my **regular** account

I'm sure this has something to do with the way that single sign on is configured in my organisation, however I'm stuck trying to find a way around it. Any ideas?

**Comment by KayUnkroth** [comment]
Do you have the same issue if you used the AAD cmdlets? For example, if you installed the AzureAD module, and you used Connect-AzureAD, would you see the same issue? My theory is that you would because the authentication library would be the same. This would help to narrow down the root cause.

**Comment by Stefvsignup** [comment]
Apologies for the late response, I had missed your reply! So I installed "Azure Active Directory PowerShell for Graph - General Availability Release 2.0.1.16" and ran the command Connect-AzureAD. He prompts me the same login BUT after putting in my admin email he also prompts me for password and allows me to successfully login with my admin account.  

I re-tried with power BI and still facing the same issue. Not sure what is causing the difference

**Comment by Stefvsignup** [comment]
As an update: I have found a workaround. 
1. shift+rightclick on the Powershell Icon in my start bar
2. login as my admin account
3. then run the "Login-PowerBI" account. 

He now signs me on automatically (without giving me the chance to fill in a password), but he signs me into the admin account. For me this item can be closed as it is no longer blocking, but off course still a difference exists in the execution between login for AAD cmdlets and PowerBI cmdlets
