### ISSUE TITLE
Cannot parse JSON output from vswhere.exe

### ISSUE THREAD

**Issue by abbgrade** [Microsoft/powerbi-powershell#76]
https://github.com/Microsoft/powerbi-powershell/blob/22a65f0b22be06fadbce758a6bc620b7839d5bd2/scripts/Build.ps1#L82

Hello,

On a machine with Powershell 4.0 i had to change this line to

` $vsInstance = $vsWhereOutput | Out-String | ConvertFrom-Json | Select-Object -First 1 `

On another machine with Powershell 5.1 this change is not necessary.

Best Regards
Steffen

**Comment by CodeCyclone** [comment]
Thanks @abbgrade, I'm checking in this fix
