### ISSUE TITLE
Could not load type 'System.Runtime.InteropServices.OSPlatform

### ISSUE THREAD

**Issue by SCartier2018** [Microsoft/powerbi-powershell#82]
Running PowerShell 5.1 on Windows 7 running .Net received following error:

Connect-PowerBIServiceAccount : Could not load type 'System.Runtime.InteropServices.OSPlatform' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, 
PublicKeyToken=cc7b13ffcd2ddd51'.
At line:1 char:1
+ Connect-PowerBIServiceAccount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...IServiceAccount:ConnectPowerBIServiceAccount) [Connect-PowerBIServiceAccount], TypeLoadException
    + FullyQualifiedErrorId : Could not load type 'System.Runtime.InteropServices.OSPlatform' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyTok 
   en=cc7b13ffcd2ddd51'.,Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAccount

**Comment by anilkumarjee** [comment]
I am facing with same issue, I do have necessary supported environments on my machine 
Windows PowerShell v3.0 (I have a v5) and up with .NET 4.6.1.

**Comment by CodeCyclone** [comment]
Please update to .NET 4.7.1 or later. Sadly this can't be fixed as it's an issue in .NET Framework. We tried to workaround this by copying netstandard.dll into the Power BI PowerShell module which fixed some environments but for others they run into this issue. Next release of this module, documentation will state 4.7.1 as the minimal version supported.

**Comment by CodeCyclone** [comment]
README was updated with newer .NET version
