### ISSUE TITLE
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array.

### ISSUE THREAD

**Issue by titoSwin** [microsoft/powerbi-powershell#98]
When I run the example code from https://docs.microsoft.com/en-us/powershell/power-bi/overview?view=powerbi-ps

```
Login-PowerBIServiceAccount
Get-PowerBIWorkspace
```

I get the error

```
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array.
At line:2 char:1
+ Get-PowerBIWorkspace
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspace], ArrayTypeMismatchException
    + FullyQualifiedErrorId : Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace
```

There was a similar issue (#60) that was marked as closed with a note to update .NET but I am running the current version and still get this erro

**Comment by simonwong7** [comment]
I also have this problem.  Tried workaround (-noprofile) from #60 and it does not work.  Also tried downgrading to 1.0.295 (as per #60) and also did not work.

I cannot use Powershell Core as I need to utilize OLEDB connections.

**Comment by atharky** [comment]
I'm in the same boat. I've tried to uninstall, reinstall, get previous versions,etc. but no luck. In Powershell core, the same is working perfectly

`Login-PowerBIServiceAccount
Get-PowerBIWorkspace`

This is the output I got after Resolve-PowerBIError -Last:

`
Message        : Attempted to access an element as a type incompatible with the array.
StackTrace     :    at System.Collections.Generic.List`1.Add(T item)
                    at Microsoft.PowerBI.Api.V2.PowerBIClient.Initialize()
                    at Microsoft.PowerBI.Api.V2.PowerBIClient..ctor(Uri baseUri, ServiceClientCredentials credentials, HttpClientHandler rootHandler, DelegatingHandler[] handlers)
                    at Microsoft.PowerBI.Common.Api.PowerBIApiClient.CreateClient(IAuthenticationFactory authenticator, IPowerBIProfile profile, IPowerBILogger logger, IPowerBISettings settings, 
                 HttpClientHandler httpClientHandler)
                    at Microsoft.PowerBI.Common.Client.PowerBIClientFactory.CreateClient(IAuthenticationFactory authenticator, IPowerBIProfile profile, IPowerBILogger logger, IPowerBISettings settings)
                    at Microsoft.PowerBI.Common.Client.PowerBIClientCmdlet.CreateClient()
                    at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
                    at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
                    at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
Exception      : System.ArrayTypeMismatchException
InvocationInfo : {Get-PowerBIWorkspace}
Line           :  Get-PowerBIWorkspace 
Position       : At line:1 char:2
                 +  Get-PowerBIWorkspace
                 +  ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11`

**Comment by nandemoii** [comment]
For the people affected by this, can you try installing >v1.0.613 of the cmdlets? If you run PowerShell (not Core) using -NoProfile, does this issue still occur?

**Comment by titoSwin** [comment]
I just updated the cmdlets and now the following script works. Thanka
```
Login-PowerBIServiceAccount
Get-PowerBIWorkspace
```

**Comment by simonwong7** [comment]
I just updated and I get the same error message:
```
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array.
At line:1 char:15
+ $workspaces = Get-PowerBIWorkspace
+               ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac
   e], ArrayTypeMismatchException
    + FullyQualifiedErrorId : Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.
   Commands.Workspaces.GetPowerBIWorkspace
```

Version of the cmdlets:

PS C:\WINDOWS\system32> Get-Module -Name MicrosoftPowerBIMgmt.Profile

```
ModuleType Version    Name                                ExportedCommands                                                                                               
---------- -------    ----                                ----------------                                                                                               
Binary     1.0.613    MicrosoftPowerBIMgmt.Profile        {Connect-PowerBIServiceAccount, Disconnect-PowerBIServiceAccount, Get-PowerBIAccessToken, Invoke-PowerBIRest...

```

Newtonsoft Version:
PS C:\WINDOWS\system32> [Newtonsoft.Json.JsonConvert].Module


MDStreamVersion    : 131072
```
FullyQualifiedName : C:\Program Files\WindowsPowerShell\Modules\MicrosoftPowerBIMgmt.Profile\1.0.613\lib\netstandard2.0\Newtonsoft.Json.dll
ModuleVersionId    : 12891e82-5fce-44a5-81e5-bbbb579c1d49
MetadataToken      : 1
ScopeName          : Newtonsoft.Json.dll
Name               : Newtonsoft.Json.dll
Assembly           : Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
CustomAttributes   : {}
ModuleHandle       : System.ModuleHandle
```

**Comment by nandemoii** [comment]
@simonwong7 Can you please try opening PowerShell using -NoProfile? The version of Newtonsoft.Json loaded into your PowerShell session is below the minimum version (12.0.2) required by the module.

**Comment by mganeshphani** [comment]
The solution of launching powershell.exe noprofile worked for me

**Comment by cvillegashak** [comment]
I still have this occuring with the noprofile. Any ideas?

**Comment by GhostROG** [comment]
I use the -NoProfile approach. Now it works :)
Using MicrosoftPowerBIMgmt V1.0.840

**Comment by alexandrevm** [comment]
Tried to load the powershell with -NoProfile but don't worked for me.

**Comment by tva77** [comment]
I had to uninstall e install again the MicrosoftPowerBIMgmt

**Comment by parag1231** [comment]
facing the same issue in powershell ISE. Please help

**Comment by EhfazR2020** [comment]
Hey @parag1231 - I had the same issue using the current (as of now) version of MicrosoftPowerBIMgmt i.e. 1.0.867, however following the -noprofile has worked for me in PowerShell ISE too. Try the below steps, hopefully should work for you as well,

1. Click on Start
2. Run
3. PowerShell_ISE.exe -noprofile

**Comment by parag1231** [comment]
![image](https://user-images.githubusercontent.com/46993628/96215278-38aad780-0f9b-11eb-9b1e-f95162898c0a.png)
Still getting the same error while executing : New-PowerBIreport cmdlet

**Comment by sajjad734** [comment]
I had tried all the option mentioned above but none worked for me. However the only way that solved my problem is that installing newtonsoft.json module. That is run the below code with administrator privilege-
Install-Module -Name newtonsoft.json -AllowClobber

**Comment by sajjad734** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/46993628/96215278-38aad780-0f9b-11eb-9b1e-f95162898c0a.png)
> Still getting the same error while executing : New-PowerBIreport cmdlet

I had tried all the option mentioned above but none worked for me. However the only way that solved my problem is that installing newtonsoft.json module. That is run the below code with administrator privilege-
Install-Module -Name newtonsoft.json -AllowClobber

**Comment by nickedase** [comment]
We have run this on an Azure Automation Account previous but out of nowhere it has now stopped working and it's returning the following error message: "Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace". Any ideas how to fix this? We have tried to update the PBI-mgmt cmdlet and adding the newtonsoft.json cmdlet.

**Comment by sherlockspreadsheets** [comment]
Best answer came from this thread comment: https://github.com/microsoft/powerbi-powershell/issues/60#issuecomment-409019796. It's apears to be a Newtonsoft.Json conflict. It worked for me to run `PowerShell_ISE.exe -noprofile`. 

Locate which Newtonsoft.Json assembly is being loaded by running:

```
[Newtonsoft.Json.JsonConvert].Module
```

With **Newtonsoft.Json.dll** loaded, the `Get-PowerBIWorkspace` cmdlet works for me. With **Newtonsoft.Json.12.0.3.dll** loaded, `Get-PowerBIWorkspace` cmdlets gives the error.

### [Newtonsoft.Json.JsonConvert].Module

MicrosoftPowerBIMgmt modules cmdlets WORKS:

> MDStreamVersion    : 131072
> FullyQualifiedName : C:\Users\Brian.Lofton\Documents\WindowsPowerShell\Modules\MicrosoftPowerBIMgmt.Profile\1.0.974\lib\netstandard2.0\Newtonsoft.Json.dll
> ModuleVersionId    : 12891e82-5fce-44a5-81e5-bbbb579c1d49
> MetadataToken      : 1
> ScopeName          : Newtonsoft.Json.dll
> Name               : Newtonsoft.Json.dll
> Assembly           : Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
> CustomAttributes   : {}
> ModuleHandle       : System.ModuleHandle


MicrosoftPowerBIMgmt modules cmdlets ERRORS:

> MDStreamVersion    : 131072
> FullyQualifiedName : C:\Users\Brian.Lofton\Documents\WindowsPowerShell\Modules\Az.Accounts\2.2.8\PreloadAssemblies\Newtonsoft.Json.12.0.3.dll
> ModuleVersionId    : 2676a2da-6edc-420e-890e-d28aa4572ee5
> MetadataToken      : 1
> ScopeName          : Newtonsoft.Json.dll
> Name               : Newtonsoft.Json.12.0.3.dll
> Assembly           : Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
> CustomAttributes   : {}
> ModuleHandle       : System.ModuleHandle

**Comment by ken-tw** [comment]
This worked with Powershell Core once I figured out how to install AzureAD for it.

`$ Import-Module AzureAD -UseWindowsPowerShell`

**Comment by davidvansickle** [comment]
Using -noprofile worked, just remember to pass the appropriate credential when connecting, otherwise it will authenticate with first.last credential which may not have sufficient permissions.

**Comment by ScriptPup** [comment]
2022 with the same bug using 1.2.1077... -noprofile doesn't work. 
The following allows me to login (again, using -noprofile and not using -noprofile to launch powershell) but the next command fails.

Windows 10

How has this issue not been resolved in 4 years, and closed? Should I open a new bug on this?

```
PS C:\WINDOWS\system32> Login-PowerBI


Environment : Public
TenantId    : 945c199a-83a2-4e80-9f8c-5a91be5752dd
UserName    : Ethan_Hammond@DELL.com



PS C:\WINDOWS\system32> Get-PowerBIActivityEvent -StartDateTime '2022-03-24' -EndDateTime '2022-03-25'
Get-PowerBIActivityEvent : Attempted to access an element as a type incompatible with the array.
At line:1 char:1
+ Get-PowerBIActivityEvent -StartDateTime '2022-03-24' -EndDateTime '20 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...BIActivityEvent:GetPowerBIActivityEvent) [Get-PowerBIActi
   vityEvent], ArrayTypeMismatchException
    + FullyQualifiedErrorId : Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.
   Commands.Admin.GetPowerBIActivityEvent
```

**Comment by mmonteroq** [comment]
Is this issue resolved?
I'm getting the same error

```
> Get-PowerBIWorkspace
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array.
At line:1 char:1
+ Get-PowerBIWorkspace
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac
   e], ArrayTypeMismatchException
    + FullyQualifiedErrorId : Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.
   Commands.Workspaces.GetPowerBIWorkspace
```

This is my setup:
```

> [Newtonsoft.Json.JsonConvert].Module


MDStreamVersion    : 131072
FullyQualifiedName : C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Newtonsoft.Json\v4.0_11.0.0.0__30ad4fe6b2a6aeed\Newtons
                     oft.Json.dll
ModuleVersionId    : 12891e82-5fce-44a5-81e5-bbbb579c1d49
MetadataToken      : 1
ScopeName          : Newtonsoft.Json.dll
Name               : Newtonsoft.Json.dll
Assembly           : Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
CustomAttributes   : {}
ModuleHandle       : System.ModuleHandle



> Get-Module -Name MicrosoftPowerBIMgmt.Profile

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.2.1104   MicrosoftPowerBIMgmt.Profile        {Connect-PowerBIServiceAccount, Disconnect-PowerBIServiceA...

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.3770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.3770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by carmbell** [comment]
Having this issue as well.
