### ISSUE TITLE
Refresh DataSet

### ISSUE THREAD

**Issue by PowerBiSmurf** [Microsoft/powerbi-powershell#99]
Hi All,

I was able to connect and to retrieve DataSets. Is there a method/way to trigger a refresh of an existing dataset? (like the "Refresh now"-Button)

Thanks

**Comment by bgribaudo** [comment]
There's not a Power BI cmdlet that does this _directly_. However, you can use the REST API to trigger a refresh in your [personal workspace](https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/refreshdataset) or in a [group workspace](https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/refreshdatasetingroup).

If you'd like to invoke one of these REST methods from Power Shell, you could try something like:
````
Invoke-PowerBIRestMethod -Url "groups/{groupId}/datasets/{datasetKey}/refreshes" -Method Post
````

**Comment by PowerBiSmurf** [comment]
Thank you! We have to add a body, but then it works!

`Invoke-PowerBIRestMethod -Url "groups/{groupId}/datasets/{datasetKey}/refreshes" -Method Post -Body '{"notifyOption": "MailOnFailure"}'`
